project:
  type: website
  output-dir: _site
  resources:
    - google88340af182e928e0.html
website:
  title: "Yijun Nie"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: about.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    link-external-newwindow: true