---
title: "Research"
---

# Research

## Publications

- 聶 逸君（2023）  
  [人的資本と既婚女性の再就職タイミング―『消費生活に関するパネル調査』データを用いて―](https://riwac.jp/admin/wp-content/uploads/2023/10/673c01c0a96a41ea0631df6e9aa2d543.pdf)  
  『現代女性とキャリア』15: 77–88.

- 聶 逸君（2025）  
  [有配偶女性のキャリアパターンと離職・転職の選択要因に関する実証分析](https://www.jstage.jst.go.jp/article/spls/17/4/17_117/_article/-char/ja/)  
  『社会政策』.

- 聶 逸君（2026）  
  [既婚女性の再就職のタイミングのコーホート比較](https://jwu.repo.nii.ac.jp/records/2000773)  
  『日本女子大学大学院 人間社会研究科紀要』第32号.
  
- 聶 逸君（2026）  
  [Gender Equality and Global City Competitiveness: The Case of Tokyo](https://moa.seoulwomen.or.kr/items/show/31270#lg=1&slide=0)  In *SEOUL SMART WOMEN REPORT Vol.1: Gender Equality and Global City Competitiveness*. Seoul Foundation of Women & Family, pp.49–60. 

## Presentations

- 聶 逸君（2022年9月）「既婚女性の再就職タイミングの変化と要因」第32回日本家族社会学会大会
- Yijun Nie（2023年7月）“Human Capital and the Timing of Mothers' Employment After Childbirth”
- 聶 逸君（2023年10月）「既婚女性の再就職のタイミングのコーホート比較」第147回社会政策学会大会
- Yijun Nie（2024年6月）“Women’s Employment and Child Care Choice in Urban China”
- 聶 逸君（2024年10月）「有配偶女性のライフコースと転職行動」第149回社会政策学会大会
- 聶 逸君（2025年9月）「母親の就業形態が妻・子どもへの家計配分に及ぼす影響」第35回家族社会学会大会

## Awards

- 2025年度 成瀬仁蔵先生記念賞
- 2024年度 第18回平塚らいてう奨励賞
- 2024年度 日本女子大学・学業成績優秀賞・研究奨励賞
- 2024年 日本女子大学・外国人留学生学業奨励賞
- 2024–2025年度 ロータリー米山記念奨学生